### ISSUE TITLE
System.InvalidOperationException: 'Nullable object must have a value.' when process a netframework4.6.1 console app

### ISSUE THREAD

**Issue by crackleeeessyp** [Washi1337/AwaitFuscator#1]
Hi, thanks for your amazing project and blogs, I tried the AwaitFuscator project, it works fine for your sample application, however, when I write a console app, it shows error: `System.InvalidOperationException: 'Nullable object must have a value.'`

![image](https://github.com/Washi1337/AwaitFuscator/assets/86238500/a9c4e406-41dd-4ec6-ab69-e85ff39a4fb8)

Below is the binary for my test console app (using netframework 4.6.1):

[ConsoleApp1.zip](https://github.com/Washi1337/AwaitFuscator/files/15387693/ConsoleApp1.zip)

The code inside it is as below:

```csharp
using System;
using System.Diagnostics;
using System.Reflection;
using System.Threading;
using System.Threading.Tasks;

namespace ConsoleApp1
{
    internal class TestClass
    {
        internal TestClass()
        {
            new Program();
        }

        internal int MemberFunc()
        {
            int a = 1;
            a++;
            return a;
        }
    }

    internal class ProgramChild: Program
    {
        protected override int TestProtected()
        {
            var a = 1;
            Console.WriteLine("protected:" + a);
            return a + 3;
        }
    }


    internal class Program
    {
        private static int field = 1;
        private int field2 = 2;
        protected string field3 = "dd";
        protected string field4 = "ddee";
        internal long field5 = 5L;
        private protected int field6 = 42;


        internal Program()
        {
            TestField();
            TestProtected();
        }

        void TestField()
        {
            field = field2 + 1;
            var result = field3 + field4 + field;
            Console.WriteLine(result + field5 + field6);
        }

        protected virtual int TestProtected()
        {
            var a = 1;
            Console.WriteLine("protected:" + a);
            return a + 2;
        }

        static void Main(string[] args)
        {
            var testClass = new TestClass();
            testClass.MemberFunc();
            var str1 = "HelloWorld";
            Console.WriteLine(str1 + TestFunc(1));

            var str2 = "TestString2";

            var a = 1;
            Console.WriteLine(str2 + TestFunc(a) + isRigth(1) + isRigth(2));

            // reflect test
            var method = typeof(Program).GetMethod("SimpleFunc", BindingFlags.NonPublic | BindingFlags.Static);
            var result = method.Invoke(null, null);
            Console.WriteLine(result);

            Console.WriteLine("bool" + integerTest() + new TestClass().MemberFunc());

            TestException();

            TestAsync();
            TestBool();
            Console.ReadKey();

        }

        static int SimpleFunc()
        {
            var a = 1;
            return a;
        }

        static async Task<bool> TestAsync()
        {
            await Task.Delay(1000);
            return true;
        }

        static bool TestBool()
        {
            return false;
        }

        static void TestException()
        {
            try
            {
                Console.WriteLine("ddd");
                throw new Exception("ee");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Exception: {ex.Message}");
            }
        }

        static int TestFunc(int b)
        {
            var a = 1 + b;
            Console.WriteLine(a);
            return a;
        }

        static bool isRigth(int a)
        {
            if(a == 1) return true;
            else return false;
        }

        static bool integerTest()
        {
            int a = 2;
            int b = 3;
            if(a+b < 5)
            {
                return true;
            }
            else
            {
                return false;
            }
        }
    }
}

```

**Comment by Washi1337** [comment]
Thanks for the catch, this problem should be fixed now.

Keep in mind Awaitfuscator does not support methods with exception handlers yet. As such, some methods remain unobfuscated. See https://blog.washi.dev/posts/awaitfuscator/#limitations.

**Comment by crackleeeessyp** [comment]
Thank you @Washi1337 for your quickly turnaround, I test it, now there is no Exception and can generate the final exe file. However, there is still a small problem, seems below function is not correctly converted and will crash with Exception:

```
        static async Task<bool> TestAsync()
        {
            await Task.Delay(1000);
            return true;
        }
```

```
{System.FieldAccessException: Attempt by method '<>AnonType_10_25.GetResult()' to access field 'ConsoleApp1.Program+<TestAsync>d__11.<>t__builder' failed.
   at <>AnonType_10_25.GetResult()
   at ConsoleApp1.Program.<TestAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ConsoleApp1.Program.TestAsync()
   at ConsoleApp1.Program.<>AnonType_8_D2.GetResult()
   at ConsoleApp1.Program.<Main>d__0.MoveNext()}
```

Not sure whether it is a bug or currently it cannot support async function?

**Comment by Washi1337** [comment]
@crackleeeessyp, thanks for noticing. I missed the error because the test application did not `await` your `TestAsync` method call, and exited before its the actual awaiter was triggered. 

I added slightly more stricter conditions that prevent awaiters accessing private members from being promoted to global anonymous types. Let me know if you still have issues.

**Comment by crackleeeessyp** [comment]
Great, now it works as expected!
